package com.tubetv.app.data.youtube

import com.tubetv.app.data.model.PlaySource
import com.tubetv.app.data.youtube.Conversions.pick
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.schabi.newpipe.extractor.Image
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream

class ConversionsTest {

    private fun image(url: String, height: Int) = Image(url, height, Image.WIDTH_UNKNOWN, Image.ResolutionLevel.fromHeight(height))

    @Test fun picksImageClosestToTarget() {
        val images = listOf(image("s", 90), image("m", 360), image("l", 720))
        assertEquals("m", images.pick(400))
        assertEquals("l", images.pick(1000))
        assertNull(emptyList<Image>().pick(360))
    }

    @Test fun picksLastImageWhenSizesUnknown() {
        assertEquals("b", listOf(image("a", Image.HEIGHT_UNKNOWN), image("b", Image.HEIGHT_UNKNOWN)).pick(360))
    }

    @Test fun hlsComesFirst() {
        val sources = Conversions.playSources("https://h/index.m3u8", "", emptyList(), emptyList(), emptyList())
        assertEquals(listOf(PlaySource.Hls("https://h/index.m3u8")), sources)
    }

    @Test fun channelTabUrlBecomesChannelUrl() {
        assertEquals("https://www.youtube.com/channel/UC1", Conversions.channelHome("https://www.youtube.com/channel/UC1/videos"))
        assertEquals("https://www.youtube.com/@nasa", Conversions.channelHome("https://www.youtube.com/@nasa"))
    }

    private fun subtitle(lang: String, auto: Boolean, format: MediaFormat = MediaFormat.VTT) =
        SubtitlesStream.Builder().setContent("https://s/$lang/$auto/${format.suffix}", true)
            .setMediaFormat(format).setLanguageCode(lang).setAutoGenerated(auto).build()

    @Test fun subtitlesAreVttWithPeopleWrittenFirst() {
        val options = Conversions.subtitleOptions(
            listOf(subtitle("en", auto = true), subtitle("ja", auto = false), subtitle("ja", auto = false, MediaFormat.TTML)),
        )
        assertEquals(listOf("https://s/ja/false/vtt", "https://s/en/true/vtt"), options.map { it.url })
        assertTrue(options[1].label.endsWith("（自动生成）"))
    }
}
